version: "2"
services:
    app:
      build: .
      volumes:
        - .:/usr/local/app
      command: rackup -p 8082 -o 0.0.0.0
      ports:
        - 8082:8082
      depends_on:
        - db
    db:
      image: mongo
